function sol = solver_RK(problem, mesh, params)
%% assymptotics at xi = 0
bc = problem.BC_L();

%% init the RK solver
options = odeset(...
    'Abstol', 1e-12...
    , 'RelTol', 1e-12 ...
    , 'NormControl', 'on' ...
    , 'NonNegative', 2 ...
    , 'MaxStep', 0.001);

[t,y] = ode45(@(x,y) problem.RK(x,y), ...
    mesh.x, bc.rhs, options);
sol.t = z_of_x(t', params)/params.z2;
sol.y = y;
end