function [out, val] = sigma(t, r, R, alpha)

xi_max = 1/(1-r)*log(G(sqrt(2*t), r)/ r);

% options = optimoptions('fminunc',...
%     'OptimalityTolerance',1e-8...
%     ,'SpecifyObjectiveGradient',false ...
%     , 'DiffMaxChange', 0.1 ...
%     , 'FiniteDifferenceType', 'central' ...
%     , 'MaxFunctionEvaluations', 2e3);
% 
% [out, val] = fminunc(...
%     @(sigma) J(sigma, t, r, R, alpha, xi_max), ...
%     -3, options);

options = optimset('TolX', 1e-9);

[out, val, flag] = fminbnd(...
    @(sigma) J(sigma, t, r, R, alpha, xi_max), ...
    -1/(2*t), 1/t, options);

end


logspace