function [out, val] = sigma(params)

% options = optimoptions('fminunc',...
%     'OptimalityTolerance',1e-8...
%     ,'SpecifyObjectiveGradient',false ...
%     , 'DiffMaxChange', 0.1 ...
%     , 'FiniteDifferenceType', 'central' ...
%     , 'MaxFunctionEvaluations', 2e3);
% 
% [out, val] = fminunc(...
%     @(sigma) J(sigma, t, r, R, alpha, xi_max), ...
%     -3, options);

options = optimset(...
      'TolX', 1e-9...
    , 'MaxFunEvals', 1e5 ...
    , 'MaxIter', 1e5 ...
    , 'PlotFcns', @optimplotfval ...
    );

% xx = [sigma, psi, gamma]

[out, val, ~] = fminsearch(...
    @(xx) J(xx, params), ...
    [3 1 1], ...
    options)

end
