function shoot
clc

n = 2.1;
lambda = n*(n+1);

jac = @(x,y)Jac_legendre(x,y,n);
mass = @(x)mass_legendre(x,[]);

options = odeset(...
    'AbsTol', 3e-10 ...
    , 'RelTol', 3e-10 ...
    , 'NormControl', 'yes' ...
...    , 'MaxStep', 1e-5 ...
    , 'Jacobian', jac ...
    , 'Mass', mass ...
    , 'MStateDependence', 'none' ...
    , 'MassSingular', 'yes' ...
    , 'InitialSlope', [1, 1/2-lambda/4] ...
    );
% x = -1;
% y = [-2/lambda; 1];
% slopes = [1; 1/2-lambda/4];
% mass(x)*slopes - jac(x,[])*y

[x,y] = ode23t(...
    @(x,y) ode_legendre(x,y, jac), ...
    [-1,1], ...
    [-2/lambda, 1], ...
    options);

figure(1011)
hold on
plot(x,y(:,1))

end